### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by NickHu** [benwr/gwipt#1]
Hi, I'd like to package your program for inclusion in [nixpkgs](https://github.com/NixOS/nixpkgs/), but I can't until you add a license.

**Comment by NickHu** [comment]
Ah, I see it's licensed here: https://github.com/benwr/gwipt/blob/0629c9c17ffefd865cbd07279dc1e6520dffd400/Cargo.toml#L7

Still, maybe some mention of it in the repo otherwise might be beneficial.

**Comment by benwr** [comment]
Sure; added text files for the licenses.
